-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TABLE "forum_users" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "forum_users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"username" varchar(50) NOT NULL,
	"email" varchar(256) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "forum_users_username_unique" UNIQUE("username"),
	CONSTRAINT "forum_users_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "forum_course_rankings" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "forum_course_rankings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"course_id" integer NOT NULL,
	"user_id" integer NOT NULL,
	"grade" numeric(5, 2) DEFAULT '0',
	"exam_difficulty" numeric(3, 2) DEFAULT '0',
	"assignment_difficulty" numeric(3, 2) DEFAULT '0',
	"interest_level" numeric(3, 2) DEFAULT '0',
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "unique_course_user_ranking" UNIQUE("course_id","user_id")
);
--> statement-breakpoint
CREATE TABLE "forum_course" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "forum_course_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title_en" varchar(256) NOT NULL,
	"title_he" varchar(256) NOT NULL,
	"description_en" text NOT NULL,
	"description_he" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"course_number" varchar(50) DEFAULT '00000' NOT NULL,
	"level" varchar(50) DEFAULT 'beginner' NOT NULL,
	"credit_points" numeric(4, 2) DEFAULT '0' NOT NULL,
	"department" varchar(256),
	"grade_average" numeric(5, 2) DEFAULT '0',
	"exam_difficulty" numeric(3, 2) DEFAULT '0',
	"assignment_difficulty" numeric(3, 2) DEFAULT '0',
	"interest_level" numeric(3, 2) DEFAULT '0',
	"overall_score" numeric(5, 2) DEFAULT '0',
	CONSTRAINT "forum_course_course_number_unique" UNIQUE("course_number")
);
--> statement-breakpoint
ALTER TABLE "forum_course_rankings" ADD CONSTRAINT "forum_course_rankings_course_id_forum_course_id_fk" FOREIGN KEY ("course_id") REFERENCES "public"."forum_course"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "forum_course_rankings" ADD CONSTRAINT "forum_course_rankings_user_id_forum_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."forum_users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "email_idx" ON "forum_users" USING btree ("email" text_ops);--> statement-breakpoint
CREATE INDEX "username_idx" ON "forum_users" USING btree ("username" text_ops);--> statement-breakpoint
CREATE INDEX "course_id_idx" ON "forum_course_rankings" USING btree ("course_id" int4_ops);--> statement-breakpoint
CREATE INDEX "user_id_idx" ON "forum_course_rankings" USING btree ("user_id" int4_ops);--> statement-breakpoint
CREATE INDEX "course_department_idx" ON "forum_course" USING btree ("department" text_ops);--> statement-breakpoint
CREATE INDEX "course_number_idx" ON "forum_course" USING btree ("course_number" text_ops);--> statement-breakpoint
CREATE INDEX "course_title_en_idx" ON "forum_course" USING btree ("title_en" text_ops);--> statement-breakpoint
CREATE INDEX "course_title_he_idx" ON "forum_course" USING btree ("title_he" text_ops);
*/